name: Terraform Apply on Main

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy terraform files to server
        run: |
          scp -i ~/.ssh/id_ed25519 -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -r terraform/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/shapyfy-infra/

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} <<'EOF'
            cd /root/shapyfy-infra/terraform
            terraform init -input=false
            terraform apply -auto-approve -var-file=dev.tfvars
          EOF
