name: Terraform Apply on Push to Main

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Terraform Apply on Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Terraform Apply on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd /root/shapyfy-infra/infra/dev
            terraform init -input=false
            terraform apply -auto-approve
          EOF
